{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "oauth2-proxy.fullname" . -}}
{{- $servicePort := .Values.service.portNumber -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
apiVersion: {{ include "capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}
{{- if .Values.ingress.annotations }}
  annotations:
{{- include "oauth2-proxy.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
{{- end }}
spec:
  {{- if and .Values.ingress.className ( eq "true" ( include "ingress.supportsIngressClassName" . ) ) }}
  ingressClassName: {{ include "oauth2-proxy.tplvalues.render" ( dict "value" .Values.ingress.className "context" $) | quote }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ include "oauth2-proxy.tplvalues.render" ( dict "value" $host "context" $) | quote }}
      http:
        paths:
{{- if $extraPaths }}
{{ include "oauth2-proxy.tplvalues.render" ( dict "value" $extraPaths "context" $) | indent 10 }}
{{- end }}
          - path: {{ include "oauth2-proxy.tplvalues.render" ( dict "value" $ingressPath "context" $) }}
            {{- if eq "true" ( include "ingress.supportsPathType" $ ) }}
            pathType: {{ include "oauth2-proxy.tplvalues.render" ( dict "value" $ingressPathType "context" $) }}
            {{- end }}
            backend: {{- include "ingress.backend" ( dict "serviceName" $serviceName "servicePort" $servicePort "context" $ )  | nindent 14 }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ include "oauth2-proxy.tplvalues.render" ( dict "value" .Values.ingress.tls "context" $) | indent 4 }}
  {{- end -}}
{{- end -}}
